dig out the reason why bloop server didn't start
For instance, when starting bloop with a version 11 JVM

```
📕 Server didn't start
Read log file:
Error: VM option 'UseZGC' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: The unlock option must precede 'UseZGC'.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```