Fix build (#238)
* Revert "Pin gha ubuntu version to 20.04 (#236)"

This reverts commit 07092394721cf16f0a2075323544e1e9af27c29b.

* missed one repo token. let's see if it helps with
```
 Error: API rate limit exceeded for 52.226.31.96. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
 ```