downgrade cats due to binary incompatibility when bumping for scala3
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Object cats.syntax.ApplyOps$.$times$greater$extension(java.lang.Object, java.lang.Object, cats.Apply)'

```